name: Validate Maven and Test coverage

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build-maven:
    name: Validate Maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B verify --file pom.xml -DskipTests=true

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Run tests
        run: |
          mvn '-Dtest=!*IntegrationTest' verify -Djacoco.destFile=exportJacoco/jacoco-ut.exec
      - name: Upload jacoco exec results
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests-jacoco
          path: exportJacoco/jacoco-ut.exec

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Run tests
        run: |
          mvn '-Dtest=*IntegrationTest' verify -Djacoco.destFile=exportJacoco/jacoco-it.exec
      - name: Upload jacoco exec results
        uses: actions/upload-artifact@v2
        with:
          name: integration-tests-jacoco
          path: exportJacoco/jacoco-it.exec

  merge-jacoco-report:
    name: Jacoco Merge Results
    needs:
      - unit-tests
      - integration-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - uses: actions/download-artifact@v2
        with:
          name: integration-tests-jacoco
          path: target/
      - uses: actions/download-artifact@v2
        with:
          name: unit-tests-jacoco
          path: target/
      - name: merge results
        run: |
          mvn jacoco:merge package jacoco:report verify -DskipTests=true
      - name: Upload jacoco coverage despite the check result
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: coverage-results-report
          path: target/site/jacoco/
          if-no-files-found: error
